apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"featureflag"},"name":"featureflag","namespace":"dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"featureflag"}},"strategy":{},"template":{"metadata":{"labels":{"app":"featureflag"}},"spec":{"containers":[{"env":[{"name":"sensitivekey","valueFrom":{"secretKeyRef":{"key":"sensitivekey","name":"featureflag-secret"}}},{"name":"unsensitivekey","valueFrom":{"configMapKeyRef":{"key":"unsensitivekey","name":"featureflag-configmap"}}}],"image":"cahityusuf/featureflag-turksat:v1","name":"featureflag-turksat","resources":{}}]}}},"status":{}}
  creationTimestamp: "2026-02-11T09:18:07Z"
  generation: 3
  labels:
    app: featureflag
  name: featureflag
  namespace: dev
  resourceVersion: "87300"
  uid: b8c2bca9-1993-421a-b9e2-fef39dde3e7f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: featureflag
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: featureflag
    spec:
      containers:
      - env:
        - name: sensitivekey
          valueFrom:
            secretKeyRef:
              key: sensitivekey
              name: featureflag-secret
        - name: unsensitivekey
          valueFrom:
            configMapKeyRef:
              key: unsensitivekey
              name: featureflag-configmap
        image: cahityusuf/featureflag-turksat:v1
        imagePullPolicy: Always
        name: featureflag-turksat
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-02-11T09:18:10Z"
    lastUpdateTime: "2026-02-11T09:18:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-02-11T09:18:07Z"
    lastUpdateTime: "2026-02-11T11:38:59Z"
    message: ReplicaSet "featureflag-7cd77f7bbb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
