apiVersion: v1
data:
  unsensitivekey: cahityusuf
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-11T09:10:46Z"
  name: featureflag-configmap
  namespace: dev
  resourceVersion: "75350"
  uid: c0a8bfef-ad5a-43a7-884e-86cdeefeff31
