apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-configmap
  name: nginx-configmap
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-configmap
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-configmap
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        env:
          - name: NGINX_CONFIGMAP_NAME
            value: nginx-configmap
          - valueFrom:
              configMapKeyRef:
                name: nginx-configmap          # The ConfigMap this value comes from.
                key: environment 
        resources: {}
status: {}
