  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: featureflag-ingress
    namespace: dev
  spec:
    ingressClassName: nginx
    rules:
      - host: cahityusuf.featureflag.com
        http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: featureflag-deployment
                  port:
                    number: 80
              path: /